/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Service.*;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.*;
/**
 *
 * @author pc
 */
public class CustomerUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUI
     */
    public CustomerUI() {
        initComponents();
        addDataToTable();
        setExtendedState(MAXIMIZED_BOTH);
        setupTableListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        phoneNumberInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        CustomerToHome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 232, 233));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("CUSTOMER LIST");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Lastname");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Phone number");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Firstname", "Lastname", "Address", "Phone no"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        insertButton.setBackground(new java.awt.Color(245, 71, 72));
        insertButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        insertButton.setForeground(new java.awt.Color(255, 255, 255));
        insertButton.setText("Insert");
        insertButton.setBorder(null);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(245, 71, 72));
        updateButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(245, 71, 72));
        deleteButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        CustomerToHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CustomerToHome.setText("Go Back to Home");
        CustomerToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerToHomeMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Firstname");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setText("CUSTOMER INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CustomerToHome)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNumberInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(86, 86, 86))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(CustomerToHome)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private void addDataToTable(){
           try{
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        CustomerService customerService = (CustomerService) theRegistry.lookup("customer");
        List<Customer> customerList =  customerService.allCustomers();
        DefaultTableModel source = (DefaultTableModel) customerTable.getModel();
        source.setRowCount(0);
        
        if (customerList != null) {
            for (Customer item : customerList) {
 
                    source.addRow(new Object[]{
                    item.getCustomerId(),
                    item.getFirstName(),
                    item.getLastName(),
                    item.getAddress(),
                    item.getTelephoneNumber(),
                });

            }
        } else {
            JOptionPane.showMessageDialog(this, "No record in the database");
        }
        
           } catch(Exception ex){
               ex.printStackTrace();
           }
    }
 int SelectedRowIndex;
 int customerId;
     private void setupTableListener(){
 customerTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    JTable source = customerTable;
                   SelectedRowIndex = source.getSelectedRow();

                    if (SelectedRowIndex >= 0) {
                         customerId = Integer.parseInt(source.getValueAt(SelectedRowIndex, 0).toString()); 
                         String customerFirstName =  source.getValueAt(SelectedRowIndex, 1).toString();
                         String customerLastName =  source.getValueAt(SelectedRowIndex, 2).toString();
                         String customerPhoneNumber =  source.getValueAt(SelectedRowIndex, 4).toString();
                         String customerAddress =  source.getValueAt(SelectedRowIndex, 3).toString();
                         firstNameInput.setText(customerFirstName);
                         lastNameInput.setText(customerLastName);
                         addressInput.setText(customerAddress);
                         firstNameInput.setText(customerFirstName);
                         phoneNumberInput.setText(customerPhoneNumber);
//                    } 
                    } 
                }
            }
        });
    }
    public static boolean isValidPhoneNumber(String phoneNumber) {
        String regex = "^\\+\\d{2,3}\\d{9}$";
        return phoneNumber.matches(regex);
    }
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
          try {
       Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
       CustomerService  customerService = (CustomerService) theRegistry.lookup("customer");    
       String firstName = firstNameInput.getText().trim();
       String lastName = lastNameInput.getText().trim();
       String address = addressInput.getText().trim();
       String phoneNumber = phoneNumberInput.getText().trim();

        if (firstName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the firstname!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if(lastName.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please fill in the lastname!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if(address.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please fill in the address!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if(phoneNumber.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please fill in the address!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if(!isValidPhoneNumber(phoneNumber)){
            JOptionPane.showMessageDialog(this, "Phone number not valid!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if(customerService.isPhoneNumberExists(phoneNumber)){
            JOptionPane.showMessageDialog(this, "Phone number already exist!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {  
          
        Customer theCustomer = new   Customer();
        theCustomer.setFirstName(firstName);
        theCustomer.setLastName(lastName);
        theCustomer.setAddress(address);
        theCustomer.setTelephoneNumber(phoneNumber);
       
        Customer ccustomerObj=  customerService.recordCustomer(theCustomer);

        if (ccustomerObj!= null) {
            addDataToTable();
            firstNameInput.setText("");
            lastNameInput.setText("");
            addressInput.setText("");
            phoneNumberInput.setText("");
            JOptionPane.showMessageDialog(this, "Data Saved");
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Saved");
        }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         if (SelectedRowIndex  < 0) {
              JOptionPane.showMessageDialog(this, "Please select a row first!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
          }
        try {
        int selectedcustomerId = customerId;
        String firstName = firstNameInput.getText().trim();
        String lastName = lastNameInput.getText().trim();
        String address = addressInput.getText().trim();
        String phoneNumber = phoneNumberInput.getText().trim();
       

        if (firstName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the category name!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if(lastName.isEmpty()){
            
        } else if(address.isEmpty()){
            
        } else if(phoneNumber.isEmpty()){
            
        }
        else {  
            
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        CustomerService customerService = (CustomerService) theRegistry.lookup("customer");
        Customer theCustomer = new Customer();
        theCustomer.setCustomerId(selectedcustomerId);
        theCustomer.setFirstName(firstName);
        theCustomer.setLastName(lastName);
        theCustomer.setAddress(address);
        theCustomer.setTelephoneNumber(phoneNumber);
       
        Customer ccustomerObj= customerService.updateCustomer(theCustomer);

        if (ccustomerObj != null) {
            addDataToTable();
            firstNameInput.setText("");
            lastNameInput.setText("");
            addressInput.setText("");
            phoneNumberInput.setText("");
            JOptionPane.showMessageDialog(this, "Data Saved");
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Saved");
        }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (SelectedRowIndex  < 0) {
              JOptionPane.showMessageDialog(this, "Please select a row first!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
          }
        try {          
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        CustomerService customerService = (CustomerService) theRegistry.lookup("customer");
        Customer theCustomer = new Customer();
        theCustomer.setCustomerId(customerId);
      
       
       Customer customerObj= customerService.deleteCustomer(theCustomer);

        if (customerObj!= null) {
            addDataToTable();
            addDataToTable();
            firstNameInput.setText("");
            lastNameInput.setText("");
            addressInput.setText("");
            phoneNumberInput.setText("");
            JOptionPane.showMessageDialog(this, "Data Deleted");
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Deleted!");
        }
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void CustomerToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerToHomeMouseClicked
       
    }//GEN-LAST:event_CustomerToHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerToHome;
    private javax.swing.JTextField addressInput;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JTextField phoneNumberInput;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
