/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Service.*;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.*;
import org.hibernate.Hibernate;

/**
 *
 * @author pc
 */
public class MenuUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public MenuUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        addDataToTable();
        setupTableListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dishCategoryTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoryIdInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        categoryNameInput = new javax.swing.JTextField();
        updateCategoryButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dishCategoryList = new javax.swing.JComboBox<>();
        categoryIdTxt1 = new javax.swing.JTextField();
        categoryIdTxt3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dishTable = new javax.swing.JTable();
        categoryIdTxt4 = new javax.swing.JTextField();
        deleteCategoryButton = new javax.swing.JButton();
        insertCategoryButton = new javax.swing.JButton();
        insertDishButton = new javax.swing.JButton();
        updateDishButton = new javax.swing.JButton();
        deleteDishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dishCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(dishCategoryTable);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("DISH INFORMATION");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Category ID");

        categoryIdInput.setEditable(false);
        categoryIdInput.setText("Select a category to get an ID");
        categoryIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryIdInputActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Category Name");

        updateCategoryButton.setBackground(new java.awt.Color(245, 71, 72));
        updateCategoryButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateCategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        updateCategoryButton.setText("Update");
        updateCategoryButton.setBorder(null);
        updateCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCategoryButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("CATEGORY INFORMATION");

        dishCategoryList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dishCategoryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishCategoryListActionPerformed(evt);
            }
        });

        categoryIdTxt1.setEditable(false);
        categoryIdTxt1.setText("Select a category to get an ID");
        categoryIdTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryIdTxt1ActionPerformed(evt);
            }
        });

        categoryIdTxt3.setEditable(false);
        categoryIdTxt3.setText("Select a category to get an ID");
        categoryIdTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryIdTxt3ActionPerformed(evt);
            }
        });

        dishTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price"
            }
        ));
        jScrollPane2.setViewportView(dishTable);

        categoryIdTxt4.setEditable(false);
        categoryIdTxt4.setText("Select a category to get an ID");
        categoryIdTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryIdTxt4ActionPerformed(evt);
            }
        });

        deleteCategoryButton.setBackground(new java.awt.Color(245, 71, 72));
        deleteCategoryButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteCategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteCategoryButton.setText("Delete");
        deleteCategoryButton.setBorder(null);
        deleteCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryButtonActionPerformed(evt);
            }
        });

        insertCategoryButton.setBackground(new java.awt.Color(245, 71, 72));
        insertCategoryButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        insertCategoryButton.setForeground(new java.awt.Color(255, 255, 255));
        insertCategoryButton.setText("Insert");
        insertCategoryButton.setBorder(null);
        insertCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCategoryButtonActionPerformed(evt);
            }
        });

        insertDishButton.setBackground(new java.awt.Color(245, 71, 72));
        insertDishButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        insertDishButton.setForeground(new java.awt.Color(255, 255, 255));
        insertDishButton.setText("Insert");
        insertDishButton.setBorder(null);
        insertDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDishButtonActionPerformed(evt);
            }
        });

        updateDishButton.setBackground(new java.awt.Color(245, 71, 72));
        updateDishButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateDishButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDishButton.setText("Insert");
        updateDishButton.setBorder(null);
        updateDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDishButtonActionPerformed(evt);
            }
        });

        deleteDishButton.setBackground(new java.awt.Color(245, 71, 72));
        deleteDishButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteDishButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteDishButton.setText("Insert");
        deleteDishButton.setBorder(null);
        deleteDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoryNameInput)
                            .addComponent(categoryIdInput, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insertCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(updateCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categoryIdTxt3)
                                            .addComponent(dishCategoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(113, 113, 113))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(insertDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(updateDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(deleteDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoryIdTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(categoryIdTxt4)))
                            .addComponent(jScrollPane2))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishCategoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryIdTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(categoryIdInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryIdTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryIdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     int selectedRowIndex;
   private void setupTableListener(){
      dishCategoryTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    JTable source = dishCategoryTable;
                   selectedRowIndex = source.getSelectedRow();

                    if (selectedRowIndex >= 0) {
                        //int selectedRowId = Integer.parseInt(source.getValueAt(selectedRowIndex, 0).toString());
                        categoryIdInput.setText(source.getValueAt(selectedRowIndex, 0).toString());
                        categoryNameInput.setText(source.getValueAt(selectedRowIndex, 1).toString());
                    } 
                }
            }
        });
    }  
    
    
 
  private void addDataToTable(){
           try{
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        DishCategoryService dishCategoryService = (DishCategoryService) theRegistry.lookup("category");
        List<DishCategory> dishCategoryList =  dishCategoryService.allDishCategories();
        DefaultTableModel dishCategoryTableModel = (DefaultTableModel) dishCategoryTable.getModel();
        dishCategoryTableModel.setRowCount(0);
        
        if (dishCategoryList != null) {
            for (DishCategory item : dishCategoryList) {
                   
                     
                    int selectedRow = dishCategoryTable.getSelectedRow();
                    if (selectedRow >= 0) {
                   
                         String dishId =  dishCategoryTableModel.getValueAt(selectedRow, 1).toString();
                         String dishName =  dishCategoryTableModel.getValueAt(selectedRow, 2).toString();
                         categoryIdInput.setText(dishId);
                         categoryNameInput.setText(dishName);
                         
                    }
               
     
                    dishCategoryTableModel.addRow(new Object[]{
                    item.getCategoryId(),
                    item.getCategoryName(),
                });
                  
                
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "No record in the database");
        }
        
           } catch(Exception ex){
               ex.printStackTrace();
           }
    }
  

   
    private void categoryIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryIdInputActionPerformed

    private void updateCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCategoryButtonActionPerformed
          if (selectedRowIndex  < 0) {
              JOptionPane.showMessageDialog(this, "Please select a row first!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
          }
        try {
        int categoryId = Integer.parseInt(categoryIdInput.getText().trim()); 
        String categoryName = categoryNameInput.getText().trim();
       

        if (categoryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the category name!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }else {  
            
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        DishCategoryService dishCategoryService = (DishCategoryService) theRegistry.lookup("category");
        DishCategory theDishCategory = new DishCategory();
        theDishCategory.setCategoryId(categoryId);
        theDishCategory.setCategoryName(categoryName);
       
        DishCategory dishCategoryObj = dishCategoryService.updateDishCategory(theDishCategory);

        if (dishCategoryObj != null) {
            addDataToTable();
            JOptionPane.showMessageDialog(this, "Data Saved");
            categoryIdInput.setText("");
             categoryNameInput.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Saved");
        }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_updateCategoryButtonActionPerformed

    private void dishCategoryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishCategoryListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishCategoryListActionPerformed

    private void categoryIdTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryIdTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryIdTxt1ActionPerformed

    private void categoryIdTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryIdTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryIdTxt3ActionPerformed

    private void categoryIdTxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryIdTxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryIdTxt4ActionPerformed

    private void deleteCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategoryButtonActionPerformed
        if (selectedRowIndex  < 0) {
              JOptionPane.showMessageDialog(this, "Please select a row first!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
          }
        try {
        int categoryId = Integer.parseInt(categoryIdInput.getText().trim()); 
        String categoryName = categoryNameInput.getText().trim();
             
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        DishCategoryService dishCategoryService = (DishCategoryService) theRegistry.lookup("category");
        DishCategory theDishCategory = new DishCategory();
        theDishCategory.setCategoryId(categoryId);
        theDishCategory.setCategoryName(categoryName);
       
        DishCategory dishCategoryObj = dishCategoryService.deleteDishCategory(theDishCategory);

        if (dishCategoryObj != null) {
            addDataToTable();
            JOptionPane.showMessageDialog(this, "Data Deleted");
            categoryIdInput.setText("");
             categoryNameInput.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Deleted!");
        }
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_deleteCategoryButtonActionPerformed

    private void insertCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCategoryButtonActionPerformed
         try {
        String categoryName = categoryNameInput.getText().trim();
       

        if (categoryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in the category name!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }else {  
            
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        DishCategoryService dishCategoryService = (DishCategoryService) theRegistry.lookup("category");
        DishCategory theDishCategory = new DishCategory();
        theDishCategory.setCategoryName(categoryName);
       
        DishCategory dishCategoryObj = dishCategoryService.recordDishCategory(theDishCategory);

        if (dishCategoryObj != null) {
            addDataToTable();
            categoryIdInput.setText("");
             categoryNameInput.setText("");
            JOptionPane.showMessageDialog(this, "Data Saved");
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Data Not Saved");
        }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_insertCategoryButtonActionPerformed

    private void insertDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDishButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertDishButtonActionPerformed

    private void updateDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDishButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDishButtonActionPerformed

    private void deleteDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDishButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryIdInput;
    private javax.swing.JTextField categoryIdTxt1;
    private javax.swing.JTextField categoryIdTxt3;
    private javax.swing.JTextField categoryIdTxt4;
    private javax.swing.JTextField categoryNameInput;
    private javax.swing.JButton deleteCategoryButton;
    private javax.swing.JButton deleteDishButton;
    private javax.swing.JComboBox<String> dishCategoryList;
    private javax.swing.JTable dishCategoryTable;
    private javax.swing.JTable dishTable;
    private javax.swing.JButton insertCategoryButton;
    private javax.swing.JButton insertDishButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton updateCategoryButton;
    private javax.swing.JButton updateDishButton;
    // End of variables declaration//GEN-END:variables
}
